### ISSUE TITLE
Use "daily overview" as home page

### ISSUE THREAD

**Issue by chadbailey59** [chadbailey59/covalent#3]
from Marty:

> Nice! I'm looking forward to using this, and if I can help out, I will. I just wish Google would include the content from https://hangouts.google.com/hangouts/_/heroku.com onto the main Hangouts page, or at least made it more accessible. Or maybe there's a way to make the home page configurable within the app? I'd love to have that view of my day when I open the app.

**Comment by gulopine** [comment]
As a workaround, I can enter that URL in the "Join Hangout from URL" screen. That'll work well enough for now so I'd consider this pretty low priority.

**Comment by chadbailey59** [comment]
Fixed in [v0.1.1](https://github.com/chadbailey59/covalent/releases/tag/v0.1.1).
