### ISSUE TITLE
Screenshare doesn't work

### ISSUE THREAD

**Issue by gulopine** [chadbailey59/covalent#8]
I don't know how much control you have over it, or what's even going on, but when I click the green "Screenshare" icon, absolutely nothing happens. I'd normally be able to select a screen or window to share, but I never see those options. Kinda sucks to be in a hangout, then you need to screenshare, only to realize that you then need to close Covalent and open a traditional Hangouts window in order to screenshare. :/

**Comment by chadbailey59** [comment]
Yep, I noticed the same thing. I'm going to attempt to debug.
